/** Compare two PDFs: word-level text diff, visual page diff, and a printable report. */
import { diffWordsWithSpace } from "diff";
import { BRAND } from "@/lib/brand";
import { pdfOut, stem, type OutFile, type ProgressFn } from "./core";
import { renderHtml } from "./layout";
import { extractPages, linesToText, renderPage, toLines, withPdfjs } from "./pdfjs";
import type { Src } from "./pages";

export type DiffPart = { value: string; added?: boolean; removed?: boolean };
export type CompareResult = { parts: DiffPart[]; added: number; removed: number; pagesA: number; pagesB: number; same: boolean };

async function docText(src: Src, onProgress?: ProgressFn) {
  const pages = await extractPages(src.bytes, { password: src.password, onProgress });
  return { text: pages.map((p) => linesToText(toLines(p))).join("\n\n"), pages: pages.length };
}

export async function compareText(a: Src, b: Src, onProgress?: ProgressFn): Promise<CompareResult> {
  const [ta, tb] = [await docText(a, (f) => onProgress?.(f * 0.4, "Reading the first file")), await docText(b, (f) => onProgress?.(0.4 + f * 0.4, "Reading the second file"))];
  if (!ta.text.trim() && !tb.text.trim()) throw new Error("Neither file has a text layer. Run OCR on both, or use the visual comparison.");
  onProgress?.(0.9, "Comparing");
  const parts = diffWordsWithSpace(ta.text, tb.text) as DiffPart[];
  const count = (pred: (p: DiffPart) => boolean | undefined) => parts.filter(pred).reduce((n, p) => n + p.value.trim().split(/\s+/).filter(Boolean).length, 0);
  return { parts, added: count((p) => p.added), removed: count((p) => p.removed), pagesA: ta.pages, pagesB: tb.pages, same: parts.every((p) => !p.added && !p.removed) };
}

export async function compareReport(a: Src, b: Src, r: CompareResult): Promise<OutFile> {
  const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const body = r.parts
    .map((p) => {
      const v = esc(p.value).replace(/\n\n+/g, "</p><p>").replace(/\n/g, "<br>");
      if (p.added) return `<span style="background-color:#d6f5dd;color:#0a5c1f;text-decoration:underline">${v}</span>`;
      if (p.removed) return `<span style="background-color:#fbd9d9;color:#8a1111;text-decoration:line-through">${v}</span>`;
      return v;
    })
    .join("");
  const html = `<h1>Comparison report</h1><p><b>Original:</b> ${esc(a.name)} (${r.pagesA} pages)<br><b>Revised:</b> ${esc(b.name)} (${r.pagesB} pages)<br><b>Changes:</b> ${r.added} words added, ${r.removed} words removed<br><span style="color:#666">Generated by ${BRAND.name} on ${new Date().toLocaleString()}</span></p><hr><p>${body}</p>`;
  return pdfOut(`compare-${stem(a.name)}-vs-${stem(b.name)}.pdf`, await renderHtml(html, { pageNumbers: true, baseSize: 10.5 }));
}

/** Render page i of both files and return a canvas highlighting pixels that differ. */
export async function visualDiff(a: Src, b: Src, page: number, scale = 1.3): Promise<{ a: string; b: string; diff: string; changed: number; pages: [number, number] }> {
  const render = async (s: Src) =>
    withPdfjs(
      s.bytes,
      async ({ pdf, pageCount }) => {
        if (page > pageCount) return { canvas: null, pageCount };
        const p = await pdf.getPage(page);
        const c = await renderPage(p, scale, { readback: true });
        p.cleanup();
        return { canvas: c, pageCount };
      },
      s.password,
    );
  const [ra, rb] = [await render(a), await render(b)];
  const w = Math.max(ra.canvas?.width ?? 0, rb.canvas?.width ?? 0);
  const h = Math.max(ra.canvas?.height ?? 0, rb.canvas?.height ?? 0);
  const out = document.createElement("canvas");
  out.width = w;
  out.height = h;
  const ctx = out.getContext("2d", { willReadFrequently: true })!;
  const get = (c: HTMLCanvasElement | null) => {
    const t = document.createElement("canvas");
    t.width = w;
    t.height = h;
    const g = t.getContext("2d", { willReadFrequently: true })!;
    g.fillStyle = "#fff";
    g.fillRect(0, 0, w, h);
    if (c) g.drawImage(c, 0, 0);
    return g.getImageData(0, 0, w, h);
  };
  const da = get(ra.canvas);
  const db = get(rb.canvas);
  const res = ctx.createImageData(w, h);
  let changed = 0;
  for (let i = 0; i < da.data.length; i += 4) {
    const la = (da.data[i] + da.data[i + 1] + da.data[i + 2]) / 3;
    const lb = (db.data[i] + db.data[i + 1] + db.data[i + 2]) / 3;
    const diff = Math.abs(la - lb) > 40;
    if (diff) changed++;
    // Faded original underneath; removed ink in red, added ink in green.
    const base = 255 - (255 - Math.min(la, lb)) * 0.25;
    res.data[i] = diff ? (la < lb ? 220 : 30) : base;
    res.data[i + 1] = diff ? (la < lb ? 40 : 160) : base;
    res.data[i + 2] = diff ? (la < lb ? 40 : 60) : base;
    res.data[i + 3] = 255;
  }
  ctx.putImageData(res, 0, 0);
  return {
    a: ra.canvas?.toDataURL("image/jpeg", 0.8) ?? "",
    b: rb.canvas?.toDataURL("image/jpeg", 0.8) ?? "",
    diff: out.toDataURL("image/png"),
    changed: Math.round((changed / Math.max(1, w * h)) * 10000) / 100,
    pages: [ra.pageCount, rb.pageCount],
  };
}
