import { BRAND } from "@/lib/brand";

export type CategoryId = "organize" | "optimize" | "edit" | "to-pdf" | "from-pdf" | "security" | "ai" | "business" | "share";

export type Values = Record<string, unknown>;

type Base = { key: string; label: string; help?: string; show?: (v: Values) => boolean; wide?: boolean };
export type OptionDef =
  | (Base & { type: "text"; placeholder?: string; default?: string })
  | (Base & { type: "textarea"; placeholder?: string; default?: string; rows?: number })
  | (Base & { type: "select"; choices: { value: string; label: string }[]; default?: string })
  | (Base & { type: "segmented"; choices: { value: string; label: string }[]; default?: string })
  | (Base & { type: "number"; min?: number; max?: number; step?: number; default?: number; suffix?: string })
  | (Base & { type: "slider"; min: number; max: number; step?: number; default?: number; format?: "percent" | "number" })
  | (Base & { type: "switch"; default?: boolean })
  | (Base & { type: "color"; default?: string })
  | (Base & { type: "password"; placeholder?: string })
  | (Base & { type: "pages"; placeholder?: string; default?: string })
  | (Base & { type: "file"; accept: string });

export type Ui =
  | "workspace"
  | "studio"
  | "organize"
  | "compare"
  | "chat"
  | "summary"
  | "scan"
  | "draw"
  | "share"
  | "board"
  | "workflow"
  | "fill-form"
  | "metadata"
  | "invoice"
  | "pos"
  | "gst"
  | "resume"
  | "audio-in"
  | "reader"
  | "privacy"
  | "fingerprint";

export type Tool = {
  slug: string;
  name: string;
  blurb: string;
  long: string;
  category: CategoryId;
  icon: string;
  ui: Ui;
  popular?: boolean;
  /** File input. Omit for tools that start from a form. */
  input?: { accept: string; multiple?: boolean; min?: number; label: string; optional?: boolean };
  options?: OptionDef[];
  cta: string;
  keywords?: string;
  steps?: string[];
  aliases?: string[];
  /** Needs a network connection or an optional server feature. */
  online?: string;
};

export const CATEGORIES: { id: CategoryId; name: string; blurb: string }[] = [
  { id: "organize", name: "Organize pages", blurb: "Merge, split, reorder, rotate, crop." },
  { id: "optimize", name: "Optimize & repair", blurb: "Make files smaller, searchable, fixed." },
  { id: "edit", name: "Edit & sign", blurb: "Text, signatures, stamps, numbers, forms." },
  { id: "to-pdf", name: "Convert to PDF", blurb: "Office files, images, web pages, ebooks." },
  { id: "from-pdf", name: "Convert from PDF", blurb: "Word, Excel, PowerPoint, images, text." },
  { id: "security", name: "Security & privacy", blurb: "Passwords, redaction, hidden data." },
  { id: "ai", name: "AI & analysis", blurb: "Ask, summarise, compare, read text from scans." },
  { id: "business", name: "Business", blurb: "GST invoices, receipts, filing prep, resumes." },
  { id: "share", name: "Share & automate", blurb: "Send files directly, whiteboard, batch workflows." },
];

const PDF = "application/pdf,.pdf";
const IMAGES = "image/png,image/jpeg,image/webp,image/gif,image/bmp,image/avif,.png,.jpg,.jpeg,.webp,.gif,.bmp,.avif,.heic";
const pdfIn = (label = "Choose a PDF"): Tool["input"] => ({ accept: PDF, label });
const pdfsIn = (min = 1, label = "Choose PDFs"): Tool["input"] => ({ accept: PDF, multiple: true, min, label });

const PAGES = (label = "Pages", def = "all"): OptionDef => ({ type: "pages", key: "pages", label, default: def, help: "e.g. all, 1-3, 5, 8-last, odd, even" });
const POSITIONS = [
  { value: "top-left", label: "Top left" },
  { value: "top", label: "Top centre" },
  { value: "top-right", label: "Top right" },
  { value: "bottom-left", label: "Bottom left" },
  { value: "bottom", label: "Bottom centre" },
  { value: "bottom-right", label: "Bottom right" },
];
const FAMILY: OptionDef = {
  type: "segmented",
  key: "family",
  label: "Font",
  default: "sans",
  choices: [
    { value: "sans", label: "Sans" },
    { value: "serif", label: "Serif" },
    { value: "mono", label: "Mono" },
  ],
};
const PAPER = (def = "A4"): OptionDef => ({
  type: "select",
  key: "paper",
  label: "Page size",
  default: def,
  choices: ["A4", "A3", "A5", "Letter", "Legal"].map((v) => ({ value: v, label: v })),
});

export const TOOLS: Tool[] = [
  /* ------------------------------------------------------------ organize */
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    blurb: "Combine PDFs into one file, in the order you choose.",
    long: "Drop in two or more PDFs, drag them into order, and merge. Bookmarks from each file are kept, and each file gets its own bookmark so the merged document is easy to navigate.",
    category: "organize",
    icon: "Combine",
    ui: "workspace",
    popular: true,
    input: pdfsIn(2, "Choose PDFs to merge"),
    options: [{ type: "switch", key: "bookmarks", label: "Add a bookmark for each file", default: true }],
    cta: "Merge PDFs",
    keywords: "combine join append",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    blurb: "Cut a PDF by page ranges, every N pages, or one file per page.",
    long: "Split by custom ranges (each range becomes its own file), into fixed-size chunks, or into single pages. Text, links and quality are untouched.",
    category: "organize",
    icon: "Scissors",
    ui: "workspace",
    popular: true,
    input: pdfIn(),
    options: [
      { type: "segmented", key: "mode", label: "Split by", default: "range", choices: [{ value: "range", label: "Ranges" }, { value: "every", label: "Every N pages" }, { value: "each", label: "Every page" }] },
      { type: "text", key: "ranges", label: "Ranges", placeholder: "1-3, 4-6, 7-last", default: "", help: "Each comma-separated range becomes one file.", show: (v) => v.mode === "range" },
      { type: "switch", key: "merge", label: "Put all ranges into a single file", default: false, show: (v) => v.mode === "range" },
      { type: "number", key: "every", label: "Pages per file", min: 1, max: 1000, default: 2, show: (v) => v.mode === "every" },
    ],
    cta: "Split PDF",
    keywords: "separate cut divide break",
  },
  {
    slug: "remove-pages",
    name: "Remove Pages",
    blurb: "Drop unwanted pages from a PDF.",
    long: "List the pages to delete and download the rest. Everything else in the file stays exactly as it was.",
    category: "organize",
    icon: "FileMinus",
    ui: "workspace",
    input: pdfIn(),
    options: [{ ...PAGES("Pages to remove", ""), placeholder: "2, 5-7, last" } as OptionDef],
    cta: "Remove pages",
    keywords: "delete drop pages",
  },
  {
    slug: "extract-pages",
    name: "Extract Pages",
    blurb: "Copy the pages you choose into a separate PDF.",
    long: "Pick pages in any order (repeats allowed) and get them as a new document.",
    category: "organize",
    icon: "FileOutput",
    ui: "workspace",
    input: pdfIn(),
    options: [{ ...PAGES("Pages to keep", ""), placeholder: "1-3, 8, 10-last" } as OptionDef],
    cta: "Extract pages",
    keywords: "select copy pages",
  },
  {
    slug: "organize-pages",
    name: "Organize Pages",
    blurb: "Drag to reorder, rotate, delete, duplicate, insert blanks.",
    long: "Lay the whole document out as a grid of page previews. Reorder by dragging, turn single pages, remove or copy them, insert blank sheets or pages from a second file, then save.",
    category: "organize",
    icon: "LayoutGrid",
    ui: "organize",
    popular: true,
    input: pdfIn(),
    steps: ["Open a PDF to lay out all its pages as small previews.", "Drag pages into order, or select some and turn, copy or remove them. Insert blank sheets or pages from a second file.", "Press “Save PDF” and download."],
    cta: "Save PDF",
    keywords: "reorder sort arrange move rearrange",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    blurb: "Turn all pages or just the ones you pick.",
    long: "Rotation is written into the page settings, so nothing is re-rendered and quality is untouched. To rotate pages individually by eye, use Organize Pages.",
    category: "organize",
    icon: "RotateCw",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "segmented", key: "angle", label: "Rotate", default: "90", choices: [{ value: "90", label: "90° right" }, { value: "180", label: "180°" }, { value: "270", label: "90° left" }] },
      PAGES("Pages to rotate"),
    ],
    cta: "Rotate",
    keywords: "turn orientation landscape portrait",
  },
  {
    slug: "mix-pdf",
    name: "Alternate & Mix",
    blurb: "Interleave pages from two or more PDFs.",
    long: "Takes page 1 from each file, then page 2, and so on. Perfect for double-sided scans where fronts and backs were scanned separately (tick “reverse” if the backs came out last-page-first).",
    category: "organize",
    icon: "Shuffle",
    ui: "workspace",
    input: pdfsIn(2, "Choose PDFs to interleave"),
    options: [
      { type: "switch", key: "reverseSecond", label: "Reverse the second file (backs scanned in reverse)", default: false },
      { type: "number", key: "chunk", label: "Pages to take from each file at a time", min: 1, max: 50, default: 1 },
    ],
    cta: "Mix pages",
    keywords: "interleave duplex double sided collate",
  },
  {
    slug: "split-by-text",
    name: "Split by Text",
    blurb: "Start a new file wherever a word or phrase appears.",
    long: "Great for batches of invoices or statements in one PDF. Every page containing the text starts a new file. Scanned files need OCR first.",
    category: "organize",
    icon: "TextSearch",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "text", key: "query", label: "Begin a new file on each page that contains", placeholder: "Invoice No", default: "" },
      { type: "switch", key: "regex", label: "Treat as a regular expression", default: false },
      { type: "switch", key: "caseSensitive", label: "Match case", default: false },
    ],
    cta: "Split by text",
  },
  {
    slug: "split-by-bookmarks",
    name: "Split by Bookmarks",
    blurb: "One file per chapter, named after the bookmark.",
    long: "Uses the PDF's bookmarks (outline) to find chapter starts. Choose the bookmark level to split on.",
    category: "organize",
    icon: "BookMarked",
    ui: "workspace",
    input: pdfIn(),
    options: [{ type: "segmented", key: "level", label: "Split at", default: "0", choices: [{ value: "0", label: "Top level" }, { value: "1", label: "Up to level 2" }, { value: "2", label: "Up to level 3" }] }],
    cta: "Split by bookmarks",
    keywords: "chapters outline sections",
  },
  {
    slug: "split-in-half",
    name: "Split Pages in Half",
    blurb: "Cut scanned two-page spreads into single pages.",
    long: "Each page becomes two pages (left/right or top/bottom). Uses crop boxes, so text and quality are kept.",
    category: "organize",
    icon: "Columns2",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "segmented", key: "axis", label: "Cut", default: "v", choices: [{ value: "v", label: "Left | Right" }, { value: "h", label: "Top / Bottom" }] },
      { type: "switch", key: "rtl", label: "Right half first (right-to-left books)", default: false, show: (v) => v.axis !== "h" },
    ],
    cta: "Split in half",
    keywords: "spread booklet scan",
  },
  {
    slug: "split-by-size",
    name: "Split by File Size",
    blurb: "Make parts small enough to email or upload.",
    long: "Packs pages into files that each stay under your size limit, for portals and email attachments with upload caps.",
    category: "organize",
    icon: "Gauge",
    ui: "workspace",
    input: pdfIn(),
    options: [{ type: "number", key: "maxMb", label: "Max size per file", min: 0.1, max: 500, step: 0.1, default: 5, suffix: "MB" }],
    cta: "Split by size",
    keywords: "email limit upload limit mb",
  },
  {
    slug: "n-up",
    name: "Pages per Sheet (N-up)",
    blurb: "2, 4, 6, 8, 9 or 16 pages on each sheet.",
    long: "Imposes several pages onto one sheet for handouts, proofs and saving paper.",
    category: "organize",
    icon: "Grid2x2",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "segmented", key: "n", label: "Pages per sheet", default: "4", choices: ["2", "4", "6", "8", "9", "16"].map((v) => ({ value: v, label: v })) },
      PAPER(),
      { type: "segmented", key: "orientation", label: "Sheet", default: "auto", choices: [{ value: "auto", label: "Auto" }, { value: "portrait", label: "Portrait" }, { value: "landscape", label: "Landscape" }] },
      { type: "switch", key: "border", label: "Draw a thin border around each page", default: true },
    ],
    cta: "Make sheets",
    keywords: "handout multiple pages one sheet print",
  },
  {
    slug: "crop-pdf",
    name: "Crop PDF",
    blurb: "Trim margins, or crop automatically to the content.",
    long: "Crop by millimetres per side, or detect the printed area and trim the white space automatically. Real crop boxes: text stays selectable.",
    category: "organize",
    icon: "Crop",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "segmented", key: "mode", label: "Mode", default: "auto", choices: [{ value: "auto", label: "Auto-trim white space" }, { value: "margins", label: "Margins" }] },
      { type: "number", key: "pad", label: "Keep a margin of", min: 0, max: 50, default: 5, suffix: "mm", show: (v) => v.mode !== "margins" },
      { type: "number", key: "top", label: "Top", min: 0, max: 200, default: 10, suffix: "mm", show: (v) => v.mode === "margins" },
      { type: "number", key: "bottom", label: "Bottom", min: 0, max: 200, default: 10, suffix: "mm", show: (v) => v.mode === "margins" },
      { type: "number", key: "left", label: "Left", min: 0, max: 200, default: 10, suffix: "mm", show: (v) => v.mode === "margins" },
      { type: "number", key: "right", label: "Right", min: 0, max: 200, default: 10, suffix: "mm", show: (v) => v.mode === "margins" },
      { ...PAGES(), show: (v) => v.mode === "margins" } as OptionDef,
    ],
    cta: "Crop",
    keywords: "trim margins whitespace",
  },
  {
    slug: "resize-pdf",
    name: "Resize Pages",
    blurb: "Fit every page onto A4, Letter or another paper size.",
    long: "Scales pages onto a standard paper size, centred and in proportion. Handy before printing mixed-size documents.",
    category: "organize",
    icon: "Scaling",
    ui: "workspace",
    input: pdfIn(),
    options: [
      PAPER(),
      { type: "segmented", key: "orientation", label: "Orientation", default: "auto", choices: [{ value: "auto", label: "Match each page" }, { value: "portrait", label: "Portrait" }, { value: "landscape", label: "Landscape" }] },
      { type: "number", key: "margin", label: "Margin", min: 0, max: 50, default: 0, suffix: "mm" },
    ],
    cta: "Resize",
    keywords: "scale paper size a4 letter fit",
  },
  {
    slug: "flip-pdf",
    name: "Flip / Mirror PDF",
    blurb: "Flip pages left to right or top to bottom.",
    long: "For transparencies, iron-on prints, and scans that came out backwards.",
    category: "organize",
    icon: "FlipHorizontal2",
    ui: "workspace",
    input: pdfIn(),
    options: [{ type: "segmented", key: "dir", label: "Flip", default: "h", choices: [{ value: "h", label: "Left ↔ right" }, { value: "v", label: "Top ↕ bottom" }] }],
    cta: "Flip",
    keywords: "mirror reverse",
  },
  {
    slug: "pdf-to-zip",
    name: "PDF to ZIP of Pages",
    blurb: "Every page as its own PDF, zipped.",
    long: "Splits each page into a separate PDF and packs them into one ZIP download.",
    category: "organize",
    icon: "Archive",
    ui: "workspace",
    input: pdfIn(),
    cta: "Make ZIP",
  },

  /* ------------------------------------------------------------ optimize */
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    blurb: "Shrink PDFs while keeping text sharp and selectable.",
    long: "Images are downsampled to a sensible resolution based on how big they appear on the page, duplicates are merged and the file structure is packed. Text, links, bookmarks and forms are untouched at every level.",
    category: "optimize",
    icon: "Minimize2",
    ui: "workspace",
    popular: true,
    input: pdfsIn(1, "Choose PDFs to compress"),
    options: [
      {
        type: "segmented",
        key: "level",
        label: "Compression",
        default: "recommended",
        choices: [
          { value: "lossless", label: "Lossless" },
          { value: "recommended", label: "Recommended" },
          { value: "strong", label: "Strong" },
          { value: "extreme", label: "Extreme" },
        ],
        help: "Recommended: images at 150 dpi. Strong: 100 dpi. Extreme: 72 dpi, with scanned pages kept at 100 dpi so they stay readable.",
      },
      { type: "switch", key: "grayscale", label: "Also convert images to black & white", default: false, show: (v) => v.level !== "lossless" },
      {
        type: "switch",
        key: "flatten",
        label: "Turn each page into a picture",
        default: false,
        show: (v) => v.level === "extreme",
        help: "Only for pages heavy with drawings, such as maps and plans. The text can no longer be selected or searched.",
      },
    ],
    cta: "Compress",
    keywords: "reduce size smaller shrink optimize mb kb email",
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    blurb: "Fix PDFs that won't open or print properly.",
    long: "Rebuilds what is broken: the file's index and list of pages, a damaged font (with one of the same letter widths), a picture or page drawing cut short. Everything that survives stays as it was, text stays text, and the result says exactly what was repaired and what could not be saved. A file that isn't a PDF at all, such as a web page saved with a .pdf name, is named for what it is.",
    category: "optimize",
    icon: "Wrench",
    ui: "workspace",
    input: pdfIn(),
    cta: "Repair",
    keywords: "fix broken corrupt damaged recover",
  },
  {
    slug: "ocr-pdf",
    name: "OCR: Searchable PDF",
    blurb: "Make scanned PDFs and photos searchable and copyable.",
    long: "Recognises the words on scanned pages (English and Hindi) right on your device and lays them invisibly over each page, leaving the scan itself untouched. The recognition engine (about 4 MB) and language data (1.5 to 3 MB) download from this site the first time and are then cached by your browser.",
    category: "optimize",
    icon: "ScanText",
    ui: "workspace",
    popular: true,
    input: { accept: `${PDF},${IMAGES}`, multiple: true, label: "Choose scanned PDFs or images" },
    options: [
      { type: "segmented", key: "lang", label: "Language", default: "eng", choices: [{ value: "eng", label: "English" }, { value: "hin", label: "Hindi" }, { value: "eng+hin", label: "Both" }] },
      { type: "switch", key: "skipText", label: "Skip pages that already have text", default: true },
      { type: "segmented", key: "dpi", label: "Accuracy", default: "300", choices: [{ value: "200", label: "Faster" }, { value: "300", label: "Best" }] },
    ],
    cta: "Make searchable",
    keywords: "ocr text recognition scan searchable copy text",
  },
  {
    slug: "grayscale-pdf",
    name: "Grayscale PDF",
    blurb: "Convert colour pages to black and white.",
    long: "Turns every page grey for cheaper printing, in the file itself: text stays sharp, selectable and searchable, links and bookmarks keep working, and pictures, gradients and spot colours turn grey too, each as light as its colour was. A page holding something that can't be converted this way is redrawn as a grey image with its text kept searchable.",
    category: "optimize",
    icon: "Contrast",
    ui: "workspace",
    input: pdfIn(),
    options: [PAGES()],
    cta: "Convert to grayscale",
    keywords: "black and white monochrome gray",
  },
  {
    slug: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    blurb: "Archive-ready PDF/A for courts, banks and records.",
    long: "Makes the file archive-ready: fonts it only names are embedded (with the same letter widths, so nothing moves), scripts and other active content are removed, annotations are set to print, and the metadata, colour profile and identifiers PDF/A requires are added. A page that can't comply as it is gets redrawn as an image, with its text kept searchable. Choose PDF/A-2B unless you were told otherwise.",
    category: "optimize",
    icon: "Archive",
    ui: "workspace",
    input: pdfIn(),
    options: [{ type: "segmented", key: "level", label: "Conformance", default: "2B", choices: [{ value: "1B", label: "PDF/A-1b" }, { value: "2B", label: "PDF/A-2b" }, { value: "3B", label: "PDF/A-3b" }] }],
    cta: "Convert to PDF/A",
    keywords: "archive archival pdfa iso 19005",
  },

  /* ---------------------------------------------------------------- edit */
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    blurb: "Add text, images, shapes, highlights and drawings.",
    long: "Retype existing lines, click to add text, drag to whiteout (the words under it are taken out of the file too) or highlight, draw freehand, add images and signatures. Everything can be moved, resized and deleted before you save.",
    category: "edit",
    icon: "PenLine",
    ui: "studio",
    popular: true,
    input: pdfIn("Choose a PDF to edit"),
    steps: ["Choose a PDF to open it in the editor.", "Pick a tool (Text, Draw, Highlight, Whiteout, shapes, Image or Signature) and click or drag on the page. Switch to Select to move, resize or delete anything.", "Press “Save PDF” and download the edited file."],
    cta: "Save PDF",
    keywords: "editor annotate add text write on pdf",
  },
  {
    slug: "edit-text",
    name: "Edit PDF Text",
    blurb: "Change existing words in a PDF.",
    long: "Click a line in the document and retype it, or empty it to delete it. The old words are taken out of the file, not just covered, so they can't be copied or found any more, and yours are set in the same place and size, in a typeface with the same widths for common fonts (Arial, Times, Calibri, Cambria, Georgia, Courier). Works on PDFs with real text; scans need OCR first.",
    category: "edit",
    icon: "TextCursor",
    ui: "studio",
    popular: true,
    input: pdfIn("Choose a PDF to edit"),
    steps: ["Choose a PDF that has real text (scans need OCR first).", "Every editable line is outlined. Click one, type the new wording (or clear it to delete the line), then click away.", "Press “Save PDF” to download the corrected file."],
    cta: "Save PDF",
    keywords: "change text modify words replace text typo",
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    blurb: "Place a signature on any page, at any size.",
    long: "Three ways to sign: draw with your mouse or fingertip, choose a cursive typeface, or take a photo of one you wrote on paper (we strip out the paper). Saved signatures stay in this browser for next time.",
    category: "edit",
    icon: "Signature",
    ui: "studio",
    popular: true,
    input: pdfIn("Choose a PDF to sign"),
    steps: ["Open the document to be signed.", "Create your signature by hand, by typing, or from a photo. It lands on the page in view; move and resize it as needed. Add the date if you want one.", "Press “Save signed PDF” and download."],
    cta: "Save signed PDF",
    keywords: "signature e-sign esign initials",
  },
  {
    slug: "fill-form",
    name: "Fill PDF Form",
    blurb: "Fill in form fields, then save or flatten.",
    long: "Lists every field in the form (text, checkboxes, choices) so you can fill them quickly, including ₹ and Hindi. Flatten to lock the answers in.",
    category: "edit",
    icon: "TextCursorInput",
    ui: "fill-form",
    input: pdfIn("Choose a fillable PDF"),
    steps: ["Choose a fillable PDF form.", "Type your answers into the fields listed on the page. Tick “Flatten” to lock them in.", "Press “Save filled PDF” and download."],
    cta: "Save filled PDF",
    keywords: "acroform fillable form fields",
  },
  {
    slug: "watermark",
    name: "Add Watermark",
    blurb: "Text or image watermark, centred, cornered or tiled.",
    long: "Add CONFIDENTIAL, DRAFT, your name or your logo. Control size, angle, colour, transparency, position and whether it sits on top of or behind the content.",
    category: "edit",
    icon: "Droplets",
    ui: "workspace",
    popular: true,
    input: pdfsIn(1, "Choose PDFs to watermark"),
    options: [
      { type: "segmented", key: "kind", label: "Watermark", default: "text", choices: [{ value: "text", label: "Text" }, { value: "image", label: "Image / logo" }] },
      { type: "text", key: "text", label: "Text", default: "CONFIDENTIAL", show: (v) => v.kind !== "image" },
      { type: "file", key: "image", label: "Image", accept: IMAGES, show: (v) => v.kind === "image" },
      { type: "segmented", key: "position", label: "Position", default: "center", choices: [{ value: "center", label: "Centre" }, { value: "tile", label: "Tiled" }, { value: "top", label: "Top" }, { value: "bottom", label: "Bottom" }] },
      { type: "slider", key: "angle", label: "Angle", min: -90, max: 90, step: 5, default: 45, format: "number" },
      { type: "slider", key: "opacity", label: "Transparency", min: 0.05, max: 1, step: 0.05, default: 0.2, format: "percent" },
      { type: "number", key: "size", label: "Text size (0 = automatic)", min: 0, max: 200, default: 0, show: (v) => v.kind !== "image" },
      { type: "slider", key: "scale", label: "Image width", min: 0.05, max: 1, step: 0.05, default: 0.4, format: "percent", show: (v) => v.kind === "image" },
      { type: "color", key: "color", label: "Colour", default: "#b42318", show: (v) => v.kind !== "image" },
      { ...FAMILY, show: (v) => v.kind !== "image" } as OptionDef,
      { type: "switch", key: "behind", label: "Place behind page content", default: false },
      PAGES(),
    ],
    cta: "Add watermark",
    keywords: "stamp confidential draft logo",
  },
  {
    slug: "page-numbers",
    name: "Add Page Numbers",
    blurb: "1, 2, 3 or “Page 1 of 10”, anywhere on the page.",
    long: "Pick the format, position, size and starting number. Skip the cover, use roman numerals, or mirror positions for double-sided printing.",
    category: "edit",
    icon: "Hash",
    ui: "workspace",
    popular: true,
    input: pdfIn(),
    options: [
      { type: "select", key: "format", label: "Format", default: "{n}", choices: [{ value: "{n}", label: "1" }, { value: "Page {n}", label: "Page 1" }, { value: "Page {n} of {total}", label: "Page 1 of 10" }, { value: "{n} / {total}", label: "1 / 10" }, { value: "- {n} -", label: "- 1 -" }] },
      { type: "select", key: "position", label: "Position", default: "bottom", choices: POSITIONS },
      { type: "segmented", key: "numerals", label: "Numerals", default: "arabic", choices: [{ value: "arabic", label: "1 2 3" }, { value: "roman", label: "i ii iii" }, { value: "ROMAN", label: "I II III" }] },
      { type: "number", key: "start", label: "Start at", min: 0, max: 99999, default: 1, help: "The number on the first numbered page" },
      { type: "number", key: "skipFirst", label: "Skip first pages", min: 0, max: 100, default: 0, help: "e.g. 1 to leave the cover unnumbered (set Start at to 2 to count it)" },
      { type: "number", key: "size", label: "Text size", min: 5, max: 48, default: 10 },
      { type: "number", key: "margin", label: "Distance from edge", min: 2, max: 60, default: 10, suffix: "mm" },
      { type: "color", key: "color", label: "Colour", default: "#222222" },
      { type: "switch", key: "mirror", label: "Mirror left/right on even pages (booklets)", default: false },
    ],
    cta: "Add page numbers",
    keywords: "pagination number pages footer",
  },
  {
    slug: "header-footer",
    name: "Headers & Footers",
    blurb: "Repeat a line of text above and below the content on each page.",
    long: "Six positions (left, centre, right at top and bottom). Use {page}, {pages}, {date}, {time}, {filename} and {title} placeholders.",
    category: "edit",
    icon: "PanelTop",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "text", key: "headerLeft", label: "Header left", default: "" },
      { type: "text", key: "headerCenter", label: "Header centre", default: "{title}" },
      { type: "text", key: "headerRight", label: "Header right", default: "{date}" },
      { type: "text", key: "footerLeft", label: "Footer left", default: "{filename}" },
      { type: "text", key: "footerCenter", label: "Footer centre", default: "" },
      { type: "text", key: "footerRight", label: "Footer right", default: "Page {page} of {pages}" },
      { type: "number", key: "size", label: "Text size", min: 5, max: 30, default: 9 },
      { type: "number", key: "margin", label: "Distance from edge", min: 2, max: 50, default: 10, suffix: "mm" },
      { type: "color", key: "color", label: "Colour", default: "#444444" },
      { type: "number", key: "skipFirst", label: "Skip first pages", min: 0, max: 100, default: 0 },
    ],
    cta: "Apply",
    keywords: "running head footer letterhead",
  },
  {
    slug: "bates",
    name: "Bates Numbering",
    blurb: "Legal exhibit numbers across one or many files.",
    long: "Gives every page a unique number such as CASE-0000001, continuing through all your files in the sequence you added them.",
    category: "edit",
    icon: "ListOrdered",
    ui: "workspace",
    input: pdfsIn(1, "Choose PDFs (numbered in this order)"),
    options: [
      { type: "number", key: "start", label: "First number", min: 0, max: 99999999, default: 1 },
      { type: "number", key: "digits", label: "Pad to", min: 3, max: 10, default: 7, suffix: "digits" },
      { type: "text", key: "prefix", label: "Before the number", default: "CASE-" },
      { type: "text", key: "suffix", label: "After the number", default: "" },
      { type: "number", key: "size", label: "Text size", min: 6, max: 24, default: 10 },
      { type: "select", key: "position", label: "Position", default: "bottom-right", choices: POSITIONS },
    ],
    cta: "Apply Bates numbers",
    keywords: "legal discovery exhibit litigation",
  },
  {
    slug: "stamp-image",
    name: "Add Image or Stamp",
    blurb: "Place a seal, logo, thumb impression or signature scan.",
    long: "Put an image on the last page, first page, every page or chosen pages, at a corner or the centre, with an optional caption (for example L.T.I. under a thumb impression).",
    category: "edit",
    icon: "Stamp",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "file", key: "image", label: "Image (PNG with transparency works best)", accept: IMAGES },
      { type: "segmented", key: "where", label: "Pages", default: "last", choices: [{ value: "last", label: "Last" }, { value: "first", label: "First" }, { value: "all", label: "All" }, { value: "custom", label: "Choose" }] },
      { ...PAGES("Which pages"), show: (v) => v.where === "custom" } as OptionDef,
      { type: "select", key: "position", label: "Position", default: "bottom-right", choices: [...POSITIONS, { value: "center", label: "Centre" }] },
      { type: "number", key: "widthMm", label: "Width", min: 5, max: 200, default: 30, suffix: "mm" },
      { type: "text", key: "caption", label: "Caption under the image", default: "", placeholder: "L.T.I." },
    ],
    cta: "Stamp",
    keywords: "seal logo thumb impression stamp company seal",
  },
  {
    slug: "flatten-pdf",
    name: "Flatten PDF",
    blurb: "Lock form answers, comments and stamps into the page.",
    long: "Makes form fields and comments a permanent part of each page: they look the same in every viewer and can't be edited afterwards. Links can stay clickable if you like.",
    category: "edit",
    icon: "Layers",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "switch", key: "forms", label: "Flatten form fields", default: true },
      { type: "switch", key: "annotations", label: "Flatten comments, stamps and drawings", default: true },
      { type: "switch", key: "keepLinks", label: "Keep clickable links", default: true },
    ],
    cta: "Flatten",
    keywords: "lock form annotations",
  },
  {
    slug: "invert-pdf",
    name: "Dark Mode PDF",
    blurb: "Light text on dark pages, easier on the eyes after dark.",
    long: "Repaints each page dark with light text. “Keep photos” leaves pictures in their real colours; “Negative” flips every colour, pictures included. The text stays searchable and copyable, and links and bookmarks keep working.",
    category: "edit",
    icon: "Moon",
    ui: "workspace",
    input: pdfIn(),
    options: [{ type: "segmented", key: "mode", label: "Style", default: "smart", choices: [{ value: "smart", label: "Keep photos" }, { value: "invert", label: "Negative" }] }, PAGES()],
    cta: "Convert",
    keywords: "invert colors negative night",
  },
  {
    slug: "metadata",
    name: "Edit Metadata",
    blurb: "Change title, author, subject and keywords.",
    long: "See and edit the document properties that search engines and PDF readers show.",
    category: "edit",
    icon: "Info",
    ui: "metadata",
    input: pdfIn(),
    steps: ["Choose a PDF to see its properties.", "Update the author, title, subject and keywords, or the app listed as creator.", "Press “Save” and download the updated file."],
    cta: "Save",
    keywords: "properties title author info",
  },
  {
    slug: "pdf-to-handwriting",
    name: "PDF to Handwriting",
    blurb: "Rewrite a PDF's text in a natural hand.",
    long: "Copies your PDF's words onto ruled paper in a handwriting style, each line slightly uneven like real writing.",
    category: "edit",
    icon: "NotebookPen",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "segmented", key: "font", label: "Hand", default: "caveat", choices: [{ value: "caveat", label: "Casual" }, { value: "kalam", label: "Neat (supports Hindi)" }] },
      { type: "segmented", key: "paper", label: "Paper", default: "ruled", choices: [{ value: "ruled", label: "Ruled" }, { value: "plain", label: "Plain" }, { value: "grid", label: "Grid" }] },
      { type: "segmented", key: "ink", label: "Ink", default: "#1e40af", choices: [{ value: "#1e40af", label: "Blue" }, { value: "#1c1c1c", label: "Black" }, { value: "#7a1f1f", label: "Red" }] },
      { type: "slider", key: "size", label: "Size", min: 12, max: 28, step: 1, default: 17, format: "number" },
    ],
    cta: "Write it out",
  },

  /* -------------------------------------------------------------- to-pdf */
  {
    slug: "images-to-pdf",
    name: "Images to PDF",
    blurb: "JPG, PNG, WebP, HEIC-exported photos → PDF.",
    long: "Each image becomes a page. Keep each photo's own size, or fit them all onto A4/Letter with margins. Drag to reorder.",
    category: "to-pdf",
    icon: "Images",
    ui: "workspace",
    popular: true,
    input: { accept: IMAGES, multiple: true, label: "Choose images" },
    options: [
      { type: "select", key: "pageSize", label: "Page size", default: "A4", choices: [{ value: "fit", label: "Same as image" }, { value: "A4", label: "A4" }, { value: "Letter", label: "Letter" }, { value: "Legal", label: "Legal" }, { value: "A5", label: "A5" }] },
      { type: "segmented", key: "orientation", label: "Orientation", default: "auto", choices: [{ value: "auto", label: "Auto" }, { value: "portrait", label: "Portrait" }, { value: "landscape", label: "Landscape" }], show: (v) => v.pageSize !== "fit" },
      { type: "number", key: "marginMm", label: "Margin", min: 0, max: 50, default: 10, suffix: "mm" },
      { type: "switch", key: "separate", label: "One PDF per image", default: false },
    ],
    cta: "Convert to PDF",
    keywords: "jpeg png webp heic photos pictures camera gallery convert",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    blurb: "DOCX to PDF laid out the way Word lays it out.",
    long: "Converts .docx files in your browser and keeps the document's own layout: page size and margins, headers and footers with page numbers, fonts, colours, tables, lists, pictures, text boxes, columns and footnotes. Headings become bookmarks and links stay clickable.",
    category: "to-pdf",
    icon: "FileType2",
    ui: "workspace",
    popular: true,
    input: { accept: ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document", multiple: true, label: "Choose Word files (.docx)" },
    cta: "Convert to PDF",
    keywords: "doc docx microsoft word",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    blurb: "Workbooks printed the way Excel prints them.",
    long: "Each sheet prints with its own page setup: paper, orientation, margins, scaling and fit to page, print area, rows repeated on every page, headers and footers with page numbers. Cells keep their fonts, fills, borders, number formats and alignment, and Excel tables, conditional formatting, pictures and charts come through.",
    category: "to-pdf",
    icon: "Sheet",
    ui: "workspace",
    input: { accept: ".xlsx,.xls,.xlsm,.ods,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel", multiple: true, label: "Choose spreadsheets" },
    options: [{ type: "segmented", key: "sheets", label: "Sheets", default: "all", choices: [{ value: "all", label: "All sheets" }, { value: "first", label: "First sheet" }] }],
    cta: "Convert to PDF",
    keywords: "xls xlsx spreadsheet ods",
  },
  {
    slug: "ppt-to-pdf",
    name: "PowerPoint to PDF",
    blurb: "Slides drawn the way PowerPoint draws them.",
    long: "Draws every slide the way PowerPoint does: the theme's fonts and colours, all of PowerPoint's shapes with their fills, outlines, arrows and shadows, pictures (old WMF and EMF drawings too), tables in their table styles, charts, SmartArt, bullets and numbering, and text shrunk by autofit. Hidden slides are left out, links stay clickable and each slide's title becomes a bookmark.",
    category: "to-pdf",
    icon: "Presentation",
    ui: "workspace",
    input: { accept: ".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation", multiple: true, label: "Choose presentations (.pptx)" },
    cta: "Convert to PDF",
    keywords: "ppt pptx slides keynote deck",
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF",
    blurb: "Paste HTML or choose an .html file.",
    long: "Typesets headings, paragraphs, lists, tables, code, quotes, images (embedded ones) and links into a clean PDF with bookmarks.",
    category: "to-pdf",
    icon: "Code",
    ui: "workspace",
    input: { accept: ".html,.htm,text/html", label: "Choose an HTML file", optional: true },
    options: [
      { type: "textarea", key: "html", label: "Or paste HTML", placeholder: "<h1>Title</h1>\n<p>Hello</p>", default: "", rows: 8, wide: true },
      PAPER(),
      { ...FAMILY, default: "sans" } as OptionDef,
    ],
    steps: ["Paste HTML, or choose an .html file.", "Pick the page size and font.", "Press “Convert to PDF” and save the result."],
    cta: "Convert to PDF",
    keywords: "web page html",
  },
  {
    slug: "markdown-to-pdf",
    name: "Markdown to PDF",
    blurb: "README and notes to a well-typeset PDF.",
    long: "Supports GitHub-style Markdown, including tables, fenced code, block quotes, links and nested lists.",
    category: "to-pdf",
    icon: "FileText",
    ui: "workspace",
    input: { accept: ".md,.markdown,.txt,text/markdown,text/plain", label: "Choose a .md file", optional: true },
    options: [{ type: "textarea", key: "md", label: "Or paste Markdown", placeholder: "# Title\n\nWrite here.", default: "", rows: 10, wide: true }, PAPER(), { ...FAMILY } as OptionDef],
    steps: ["Paste Markdown, or choose a .md file.", "Pick the page size and font.", "Press “Convert to PDF” and save the result."],
    cta: "Convert to PDF",
    keywords: "md readme",
  },
  {
    slug: "csv-to-pdf",
    name: "CSV to PDF",
    blurb: "Tables from CSV/TSV, paginated with headers.",
    long: "Reads CSV properly (quoted commas, line breaks inside cells), and prints a clean table with the header row repeated.",
    category: "to-pdf",
    icon: "Table",
    ui: "workspace",
    input: { accept: ".csv,.tsv,.txt,text/csv", multiple: true, label: "Choose CSV files" },
    options: [{ type: "switch", key: "header", label: "First row is a header", default: true }, PAPER()],
    cta: "Convert to PDF",
  },
  {
    slug: "create-pdf",
    name: "Text to PDF",
    blurb: "Turn plain writing into a clean PDF.",
    long: "Write a document from scratch, or paste text. Supports Markdown formatting (# headings, **bold**, lists) and ₹, Hindi and symbols.",
    category: "to-pdf",
    icon: "FilePlus",
    ui: "workspace",
    input: { accept: ".txt,text/plain", label: "Choose a .txt file", optional: true },
    options: [
      { type: "text", key: "title", label: "Title", default: "" },
      { type: "textarea", key: "body", label: "Text", placeholder: "Start typing…", default: "", rows: 12, wide: true },
      { type: "switch", key: "markdown", label: "Format with Markdown", default: true },
      PAPER(),
      { ...FAMILY } as OptionDef,
    ],
    steps: ["Write in the box, paste from anywhere, or open a .txt file.", "Add a title and pick the page size and font. Markdown formatting works.", "Press “Create PDF” and download."],
    cta: "Create PDF",
    keywords: "txt to pdf text new blank document",
  },
  {
    slug: "ebook-to-pdf",
    name: "eBook (EPUB) to PDF",
    blurb: "EPUB chapters in order, with images and cover.",
    long: "Reads the book's spine in order, keeps images and the cover, and adds chapter bookmarks. DRM-protected books can't be converted.",
    category: "to-pdf",
    icon: "BookOpen",
    ui: "workspace",
    input: { accept: ".epub,application/epub+zip", label: "Choose an EPUB" },
    options: [PAPER("A5")],
    cta: "Convert to PDF",
    keywords: "epub ebook book",
  },
  {
    slug: "scan-document",
    name: "Scan to PDF",
    blurb: "Use your camera: crop, straighten, clean up, save.",
    long: "Snap pages with your phone or webcam (or add photos). Drag the corners to straighten each page, pick a filter like crisp black & white, then save one PDF. Optional OCR makes it searchable.",
    category: "to-pdf",
    icon: "Camera",
    ui: "scan",
    popular: true,
    steps: ["Allow camera access, or add photos of your pages.", "Drag the corners to straighten each page and pick a filter such as crisp black & white.", "Press “Save PDF”. Turn on OCR first if you want searchable text."],
    cta: "Save PDF",
    keywords: "scanner camera photo document scanner",
  },
  {
    slug: "text-to-handwriting",
    name: "Text to Handwriting",
    blurb: "Typed text written out by hand on ruled paper.",
    long: "Paste text and get pages that look handwritten: ruled, plain or grid paper, blue or black ink, natural wobble. Hindi supported.",
    category: "to-pdf",
    icon: "PenTool",
    ui: "workspace",
    options: [
      { type: "text", key: "heading", label: "Heading (optional)", default: "" },
      { type: "textarea", key: "body", label: "Text", placeholder: "Write what should appear in handwriting…", default: "", rows: 10, wide: true },
      { type: "segmented", key: "font", label: "Hand", default: "caveat", choices: [{ value: "caveat", label: "Casual" }, { value: "kalam", label: "Neat (supports Hindi)" }] },
      { type: "segmented", key: "paper", label: "Paper", default: "ruled", choices: [{ value: "ruled", label: "Ruled" }, { value: "plain", label: "Plain" }, { value: "grid", label: "Grid" }] },
      { type: "segmented", key: "ink", label: "Ink", default: "#1e40af", choices: [{ value: "#1e40af", label: "Blue" }, { value: "#1c1c1c", label: "Black" }, { value: "#7a1f1f", label: "Red" }] },
      { type: "slider", key: "size", label: "Size", min: 12, max: 28, step: 1, default: 17, format: "number" },
      { type: "slider", key: "wobble", label: "Messiness", min: 0, max: 2, step: 0.1, default: 1, format: "number" },
    ],
    steps: ["Enter the words you want handwritten.", "Choose the handwriting, paper, ink colour and size.", "Press “Make handwriting PDF” and download."],
    cta: "Make handwriting PDF",
    keywords: "handwritten assignment notes",
  },
  {
    slug: "handwriting-to-pdf",
    name: "Draw to PDF",
    blurb: "Sketch or write on a pad, page by page.",
    long: "A drawing pad with pen, highlighter and eraser. Take notes or sketch over several pages, then save the lot as one PDF.",
    category: "to-pdf",
    icon: "PencilLine",
    ui: "draw",
    steps: ["Write or sketch on the pad with a mouse, finger or stylus.", "Add more pages, change the pen, or switch the paper style as you go.", "Press “Save PDF” to download every page."],
    cta: "Save PDF",
    keywords: "draw sketch notes pad",
  },
  {
    slug: "audio-to-pdf",
    name: "Audio to PDF",
    blurb: "Dictate, or transcribe recordings into a PDF.",
    long: "Speak and watch the words appear, or upload a recording to transcribe (when transcription is enabled on this site). Edit the text, then save a PDF transcript.",
    category: "to-pdf",
    icon: "Mic",
    ui: "audio-in",
    steps: ["Press the microphone and speak, or upload a recording to transcribe (when enabled on this site).", "Check and edit the transcript.", "Press “Save transcript PDF”."],
    cta: "Save transcript PDF",
    keywords: "speech to text dictation transcription voice",
    online: "Dictation uses your browser's speech service; file transcription needs the site's AI key.",
  },

  /* ------------------------------------------------------------ from-pdf */
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    blurb: "Editable DOCX with headings, lists, tables and images.",
    long: "Rebuilds the document's structure as editable Word content. Choose “Exact look” to get each page as a picture in Word when appearance matters more than editing. Scans need OCR first.",
    category: "from-pdf",
    icon: "FileOutput",
    ui: "workspace",
    popular: true,
    input: pdfIn(),
    options: [
      { type: "segmented", key: "mode", label: "Output", default: "editable", choices: [{ value: "editable", label: "Editable text" }, { value: "exact", label: "Exact look" }] },
      { type: "switch", key: "pageBreaks", label: "Keep page breaks", default: true, show: (v) => v.mode !== "exact" },
      { type: "switch", key: "images", label: "Include pictures", default: true, show: (v) => v.mode !== "exact" },
    ],
    cta: "Convert to Word",
    keywords: "docx doc word editable",
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    blurb: "Tables become real rows and columns.",
    long: "Rebuilds each table with its header, shading and lines. Figures become numbers and percentages shown as printed, dates become dates, and codes keep their leading zeros. One sheet per page, or everything on one sheet, where a table that runs over several pages (a bank statement) becomes one.",
    category: "from-pdf",
    icon: "Table2",
    ui: "workspace",
    popular: true,
    input: pdfIn(),
    options: [{ type: "switch", key: "oneSheet", label: "Put all pages on one sheet", default: false }],
    cta: "Convert to Excel",
    keywords: "xlsx spreadsheet table extract bank statement",
  },
  {
    slug: "pdf-to-ppt",
    name: "PDF to PowerPoint",
    blurb: "Slides with editable text, laid out like your pages.",
    long: "Each page becomes a slide. Its text comes back as editable text boxes with the same fonts, sizes, colours, bullets and numbering, placed over the page's own graphics and pictures. Choose “Exact look” to get each page as a picture, with its text in the speaker notes. Scanned pages come through as pictures.",
    category: "from-pdf",
    icon: "MonitorPlay",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "segmented", key: "mode", label: "Output", default: "editable", choices: [{ value: "editable", label: "Editable text" }, { value: "exact", label: "Exact look" }] },
      { type: "switch", key: "notes", label: "Put page text in speaker notes", default: true, show: (v) => v.mode === "exact" },
    ],
    cta: "Convert to PowerPoint",
    keywords: "pptx slides presentation",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG / PNG",
    blurb: "Every page as an image, at the resolution you need.",
    long: "Renders pages as JPG, PNG or WebP at screen, print or high resolution. Multiple pages come as a ZIP too.",
    category: "from-pdf",
    icon: "Image",
    ui: "workspace",
    popular: true,
    input: pdfIn(),
    options: [
      { type: "segmented", key: "format", label: "Format", default: "jpg", choices: [{ value: "jpg", label: "JPG" }, { value: "png", label: "PNG" }, { value: "webp", label: "WebP" }] },
      { type: "segmented", key: "dpi", label: "Resolution", default: "150", choices: [{ value: "96", label: "Screen" }, { value: "150", label: "Standard" }, { value: "300", label: "Print" }] },
      PAGES(),
    ],
    cta: "Convert to images",
    keywords: "jpeg png image picture convert",
  },
  {
    slug: "extract-images",
    name: "Extract Images",
    blurb: "Get every image out of a PDF, untouched.",
    long: "Copies every picture out unchanged, byte for byte (JPEGs aren't re-compressed), and names each one after the page it was on.",
    category: "from-pdf",
    icon: "ImageDown",
    ui: "workspace",
    input: pdfIn(),
    options: [{ type: "segmented", key: "format", label: "Save as", default: "original", choices: [{ value: "original", label: "Original format" }, { value: "png", label: "All PNG" }] }],
    cta: "Extract images",
    keywords: "pictures photos get images",
  },
  {
    slug: "extract-text",
    name: "PDF to Text",
    blurb: "All the text as a .txt file.",
    long: "Text in reading order, or with the page layout preserved (columns and tables stay aligned). Scanned files need OCR first.",
    category: "from-pdf",
    icon: "Type",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "segmented", key: "layout", label: "Mode", default: "reading", choices: [{ value: "reading", label: "Reading order" }, { value: "layout", label: "Keep layout" }] },
      { type: "switch", key: "pageBreaks", label: "Mark page breaks", default: true },
    ],
    cta: "Extract text",
    keywords: "txt copy text",
  },
  {
    slug: "pdf-to-html",
    name: "PDF to HTML",
    blurb: "A readable web page, or an exact-looking one.",
    long: "“Readable” rebuilds headings, lists, tables, pictures and charts as clean HTML that works on phones, with the links still working. “Exact look” shows the pages as they are, with selectable text.",
    category: "from-pdf",
    icon: "FileCode",
    ui: "workspace",
    input: pdfIn(),
    options: [{ type: "segmented", key: "mode", label: "Style", default: "reflow", choices: [{ value: "reflow", label: "Readable" }, { value: "exact", label: "Exact look" }] }],
    cta: "Convert to HTML",
    keywords: "web page html",
  },
  {
    slug: "pdf-to-markdown",
    name: "PDF to Markdown",
    blurb: "Headings, lists and tables as Markdown.",
    long: "Great for docs, wikis, Notion and AI tools. Links, bold and italics come along, and text set in columns reads in order.",
    category: "from-pdf",
    icon: "FileText",
    ui: "workspace",
    input: pdfIn(),
    cta: "Convert to Markdown",
    keywords: "md notion obsidian",
  },
  {
    slug: "pdf-to-csv",
    name: "PDF to CSV",
    blurb: "Table data as comma-separated values.",
    long: "Columns are detected from the layout so each value lands in its own field.",
    category: "from-pdf",
    icon: "Table",
    ui: "workspace",
    input: pdfIn(),
    cta: "Convert to CSV",
  },
  {
    slug: "pdf-to-epub",
    name: "PDF to EPUB",
    blurb: "A reflowable ebook for Kindle apps and e-readers.",
    long: "Chapters are found from the headings, page 1 becomes the cover, pictures and charts stay in place, and the text reflows to any screen size.",
    category: "from-pdf",
    icon: "Library",
    ui: "workspace",
    input: pdfIn(),
    options: [{ type: "text", key: "title", label: "Book title (optional)", default: "" }, { type: "text", key: "author", label: "Author (optional)", default: "" }],
    cta: "Convert to EPUB",
    keywords: "ebook kindle epub",
  },
  {
    slug: "pdf-to-audio",
    name: "PDF to Audio",
    blurb: "Listen to a PDF, read aloud.",
    long: "Reads the document aloud with your device's voices: play, pause, skip, change speed, follow along. Download an MP3 when the site's speech service is enabled.",
    category: "from-pdf",
    icon: "Volume2",
    ui: "reader",
    input: pdfIn(),
    steps: ["Choose a PDF with text.", "Pick a voice and speed, then press play. The sentence being read is highlighted.", "Download an MP3 if the site has a speech service enabled."],
    cta: "Read aloud",
    keywords: "text to speech listen tts audiobook",
  },

  /* ------------------------------------------------------------ security */
  {
    slug: "encrypt-pdf",
    name: "Protect PDF",
    blurb: "Add a password with AES-256 encryption.",
    long: "Anyone opening the file will need the password. You can also restrict printing, copying and editing.",
    category: "security",
    icon: "Lock",
    ui: "workspace",
    popular: true,
    input: pdfsIn(1, "Choose PDFs to protect"),
    options: [
      { type: "password", key: "userPassword", label: "Password to open", placeholder: "At least 4 characters" },
      { type: "password", key: "ownerPassword", label: "Permissions password (optional)", placeholder: "Leave empty to lock permissions" },
      { type: "segmented", key: "printing", label: "Printing", default: "high", choices: [{ value: "high", label: "Allowed" }, { value: "low", label: "Low quality" }, { value: "none", label: "Not allowed" }] },
      { type: "switch", key: "copying", label: "Allow copying text", default: false },
      { type: "switch", key: "modifying", label: "Allow editing", default: false },
      { type: "switch", key: "fillingForms", label: "Allow filling forms", default: true },
    ],
    cta: "Protect PDF",
    keywords: "encrypt password lock secure",
  },
  {
    slug: "remove-password",
    name: "Remove Password",
    blurb: "Unlock a PDF you have the password for.",
    long: "Give the password one time and get back a copy that opens freely. Files that only block printing or copying unlock with no password at all. This tool can't recover a password you've forgotten.",
    category: "security",
    icon: "LockOpen",
    ui: "workspace",
    popular: true,
    input: pdfIn(),
    options: [{ type: "password", key: "password", label: "Current password (leave empty for restriction-only files)" }],
    cta: "Unlock PDF",
    aliases: ["unlock-pdf"],
    keywords: "unlock decrypt remove protection restrictions",
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    blurb: "Black out areas permanently (text underneath is removed).",
    long: "Mark anything sensitive with a box. A drawn black shape only hides things; this deletes the text and images beneath it from the file. Everything outside the boxes remains searchable.",
    category: "security",
    icon: "SquareSlash",
    ui: "studio",
    popular: true,
    input: pdfIn("Choose a PDF to redact"),
    steps: ["Choose the PDF to redact.", "Drag boxes over anything sensitive, or search for a word or number and mark every match.", "Press “Redact and save”. The covered text and images are removed from the file for good."],
    cta: "Redact and save",
    keywords: "black out censor hide remove sensitive",
  },
  {
    slug: "auto-redact",
    name: "Auto-Redact PII",
    blurb: "Spots Aadhaar, PAN, card numbers, phones and emails, then blacks them out.",
    long: "Scans the text for personal data (Aadhaar, PAN, GSTIN, IFSC, UPI IDs, card numbers with checksum, phone numbers, emails, passport, bank accounts and more) plus any words you add, lets you review the matches, then permanently redacts them.",
    category: "security",
    icon: "ShieldOff",
    ui: "privacy",
    input: pdfIn(),
    steps: ["Choose a PDF with text (scans need OCR first).", "Review what was found: Aadhaar, PAN, card and phone numbers, emails and more. Untick anything that should stay, or add your own words.", "Press “Redact selected” to download the cleaned PDF and a log of what was removed."],
    cta: "Redact selected",
    keywords: "pii personal data aadhaar pan gdpr dpdp",
  },
  {
    slug: "privacy-scanner",
    name: "Privacy Risk Scanner",
    blurb: "See what personal data and hidden info a PDF contains.",
    long: "A report of personal data in the text (by page) plus hidden risks: metadata, embedded files, JavaScript, form data, comments. Nothing is changed.",
    category: "security",
    icon: "ScanSearch",
    ui: "privacy",
    input: pdfIn(),
    steps: ["Choose a PDF.", "See the personal data in the text, page by page, plus hidden risks like metadata, attachments and scripts.", "Redact what was found or remove the hidden data with one click, or download the report."],
    cta: "Scan",
    keywords: "privacy audit check pii",
  },
  {
    slug: "sanitize-pdf",
    name: "Remove Hidden Data",
    blurb: "Strip metadata, scripts, attachments, comments.",
    long: "Removes author names, software info, embedded files, JavaScript and optionally links, comments and form fields before you share a document.",
    category: "security",
    icon: "Eraser",
    ui: "workspace",
    input: pdfIn(),
    options: [
      { type: "switch", key: "metadata", label: "Metadata (author, software, dates)", default: true },
      { type: "switch", key: "javascript", label: "JavaScript and auto-actions", default: true },
      { type: "switch", key: "attachments", label: "Embedded files", default: true },
      { type: "switch", key: "annotations", label: "Comments and markup", default: false },
      { type: "switch", key: "links", label: "Links", default: false },
      { type: "switch", key: "forms", label: "Flatten form fields", default: false },
    ],
    cta: "Clean PDF",
    keywords: "sanitize metadata scrub clean hidden",
  },
  {
    slug: "fingerprint",
    name: "Fingerprint PDF",
    blurb: "Checksums that prove a file hasn't changed by a single byte.",
    long: "Generates checksums of the exact bytes, plus the PDF's internal IDs and properties. Paste a hash you were given to check a file hasn't been altered.",
    category: "security",
    icon: "Fingerprint",
    ui: "fingerprint",
    input: { accept: "*/*", multiple: true, label: "Choose files" },
    steps: ["Choose one or more files (any type).", "Copy its SHA-256 (or SHA-512, MD5, SHA-1) value, and see the PDF's internal IDs and properties.", "Paste a hash you were given to check the file hasn't been changed."],
    cta: "Fingerprint",
    keywords: "hash checksum sha256 md5 verify integrity tamper",
  },

  /* ------------------------------------------------------------------ ai */
  {
    slug: "chat-pdf",
    name: "Chat with PDF",
    blurb: "Ask questions and get answers with page references.",
    long: "Ask anything about the document. Answers quote the relevant passages with page numbers. Works on this device; when the site has an AI service enabled you can switch to AI answers, which send only the relevant passages, never the file.",
    category: "ai",
    icon: "MessageSquareText",
    ui: "chat",
    popular: true,
    input: pdfIn(),
    steps: ["Choose a PDF with text.", "Ask a question, or tap one of the suggestions.", "Read the answer and check the quoted passages and page numbers it came from."],
    cta: "Ask",
    keywords: "ai chatgpt question answer",
  },
  {
    slug: "summarize",
    name: "AI PDF Summarizer",
    blurb: "Key points, facts and keywords in seconds.",
    long: "Picks out the most important sentences, dates, amounts and keywords, with page references. Optional AI summaries when enabled on this site.",
    category: "ai",
    icon: "Sparkles",
    ui: "summary",
    popular: true,
    input: pdfIn(),
    steps: ["Choose a PDF with text.", "Read the key points, facts and keywords. Use the slider for a shorter or longer summary.", "Copy the summary, or download a PDF copy."],
    cta: "Summarize",
    keywords: "summary tldr key points",
  },
  {
    slug: "compare-pdfs",
    name: "Compare PDFs",
    blurb: "Spot every change between two versions.",
    long: "Word-by-word differences highlighted, plus a visual page-by-page overlay that catches layout and image changes. Download a comparison report.",
    category: "ai",
    icon: "GitCompare",
    ui: "compare",
    steps: ["Choose the original PDF and the changed version.", "Press “Compare” to see every word added or removed.", "Switch to Visual to spot layout and image changes, or make a PDF report."],
    cta: "Compare",
    keywords: "diff difference versions changes redline",
  },

  /* ------------------------------------------------------------ business */
  {
    slug: "gst-invoice",
    name: "GST Invoice Generator",
    blurb: "Tax invoice with CGST/SGST or IGST worked out for you.",
    long: "Fill in seller, buyer and items. Intra-state vs inter-state tax is decided from the state codes, with HSN summary, amount in words, bank details and a UPI QR code for payment. Your details are remembered in this browser.",
    category: "business",
    icon: "Receipt",
    ui: "invoice",
    popular: true,
    steps: ["Enter your business details once. They're remembered in this browser.", "Add the buyer and the items. CGST/SGST or IGST is worked out from the state codes.", "Press “Download invoice” for a PDF with HSN summary, amount in words and a UPI QR code."],
    cta: "Download invoice",
    keywords: "bill invoice gst india tax invoice cgst sgst igst",
  },
  {
    slug: "pos-bill",
    name: "POS Receipt",
    blurb: "58/80 mm thermal-style bills with GST and UPI QR.",
    long: "Quick shop receipts sized for thermal printers, with GST (inclusive or extra), discounts and a payment QR.",
    category: "business",
    icon: "Ticket",
    ui: "pos",
    steps: ["Enter the shop details and choose 58 mm or 80 mm paper.", "Add items, any discount and the GST rate.", "Press “Download receipt” and print it on a thermal printer."],
    cta: "Download receipt",
    keywords: "receipt thermal printer shop billing",
  },
  {
    slug: "gst-filing",
    name: "GST Filing Prep",
    blurb: "Rate-wise summary of your invoices for GSTR-1/3B.",
    long: "Enter or import invoices (CSV) and get B2B and B2C summaries by tax rate with CGST/SGST/IGST totals, as PDF and CSV. A working paper to cross-check against the GST portal.",
    category: "business",
    icon: "ClipboardList",
    ui: "gst",
    steps: ["Type in your invoices, or import them from a CSV.", "Check the B2B and B2C summary by tax rate.", "Download the working paper as PDF and CSV to cross-check against the GST portal."],
    cta: "Download summary",
    keywords: "gstr1 gstr3b return filing summary",
  },
  {
    slug: "resume",
    name: "Resume Builder",
    blurb: "A clean, ATS-friendly CV as PDF.",
    long: "Fill in sections, pick a template, download. Real text (not an image), so job portals can read it. Saved in this browser as you type.",
    category: "business",
    icon: "Briefcase",
    ui: "resume",
    steps: ["Add your details, work history, education and skills. Everything you type is saved in this browser as you go.", "Choose a layout and an accent colour.", "Press “Download resume” for a text-based PDF that job portals can read."],
    cta: "Download resume",
    keywords: "cv resume job",
  },

  /* --------------------------------------------------------------- share */
  {
    slug: "p2p-share",
    name: "P2P File Share",
    blurb: "Send files straight to another device, no upload.",
    long: "Get a code or QR, open it on the other device, and the files stream directly between browsers over an encrypted connection. Optional password adds end-to-end AES-256 encryption. Keep both devices connected until the transfer finishes.",
    category: "share",
    icon: "Share2",
    ui: "share",
    steps: ["Add the files you want to send and press Share.", "Open the link or scan the QR code on the other device (or type the code).", "The files stream straight across. Add a password for extra end-to-end encryption."],
    cta: "Share",
    keywords: "send transfer airdrop share file",
    online: "Needs an internet connection to connect the two devices.",
  },
  {
    slug: "whiteboard",
    name: "Collaborative Whiteboard",
    blurb: "Sketch together in real time, export to PDF.",
    long: "Pens, shapes, text and sticky notes across several pages. Invite others with a link and everyone sketches on the same board in real time, browser to browser. Bring in a PDF to annotate, then export as PDF or PNG.",
    category: "share",
    icon: "PencilRuler",
    ui: "board",
    steps: ["Start drawing with pens, shapes, text and sticky notes. Add pages as you need them.", "Press Share to invite others; they draw with you live.", "Export the board as a PDF or PNG."],
    cta: "Export",
    keywords: "draw collaborate annotate board",
    online: "Live collaboration needs an internet connection.",
  },
  {
    slug: "workflow",
    name: "Batch Workflow",
    blurb: "Line up several tools and apply them to a batch of files.",
    long: "Build a pipeline, for example rotate → add page numbers → watermark → compress → protect, then run it on any number of PDFs in one go. Workflows are saved in this browser.",
    category: "share",
    icon: "Workflow",
    ui: "workflow",
    input: pdfsIn(1, "Choose PDFs to process"),
    steps: ["Build a list of steps, such as rotate, add page numbers, watermark, compress and protect.", "Add the PDFs to process, any number of them.", "Press “Run workflow” to process them all and download the results."],
    cta: "Run workflow",
    keywords: "batch automate pipeline bulk",
  },
];

export const TOOL_BY_SLUG: Record<string, Tool> = Object.fromEntries(TOOLS.flatMap((t) => [[t.slug, t], ...(t.aliases ?? []).map((a) => [a, t])]));

export const POPULAR = TOOLS.filter((t) => t.popular);

export function searchTools(q: string): Tool[] {
  const s = q.trim().toLowerCase();
  if (!s) return TOOLS;
  const words = s.split(/\s+/);
  return TOOLS.map((t) => {
    const name = t.name.toLowerCase();
    const hay = `${name} ${t.blurb} ${t.keywords ?? ""} ${t.slug.replace(/-/g, " ")}`.toLowerCase();
    let score = 0;
    if (name.startsWith(s)) score += 10;
    if (name.includes(s)) score += 6;
    for (const w of words) if (hay.includes(w)) score += 2;
    return { t, score };
  })
    .filter((x) => x.score >= Math.max(2, words.length * 2))
    .sort((a, b) => b.score - a.score)
    .map((x) => x.t);
}

export function defaultsOf(defs: OptionDef[] = []): Values {
  const o: Values = {};
  for (const d of defs) if ("default" in d && d.default !== undefined) o[d.key] = d.default;
  return o;
}

export const FAQ: { q: string; a: string }[] = [
  { q: `Is ${BRAND.name} really free?`, a: "Yes. Every tool costs nothing: no account, no page caps, and nothing stamped on your files." },
  { q: "Are my files uploaded?", a: "No. Files are opened and processed by your own browser. They never reach a server. Apart from an anonymous visit count, the only things that use the network are optional: AI answers (if this site enables them) send the question plus relevant passages of text, never the file; P2P Share and the whiteboard connect two browsers directly." },
  { q: "Does it work offline?", a: "Once a tool's engine has loaded, most tools keep working without a connection. OCR downloads its language data on first use and caches it." },
  { q: "How big can my files be?", a: "There's no cap from us. Your device does the processing, so its free memory is the real ceiling. On a phone, split or compress very large files first." },
  { q: "Can it edit scanned PDFs?", a: "Run OCR (Searchable PDF) first. That adds a text layer, after which you can search, copy, convert, redact and edit text." },
  { q: "Is the redaction safe?", a: "Yes. Redacted areas are burned into a fresh image of the page and the original text, images and vectors under them are removed. Everything outside the boxes stays searchable." },
  { q: "How strong is the password protection?", a: "Protect PDF encrypts with AES-256, the top level defined in the PDF standard. Choose a long password; if it's lost, nobody (us included) can get it back." },
];
