import {
  Archive,
  BookMarked,
  BookOpen,
  Briefcase,
  Camera,
  ClipboardList,
  Code,
  Columns2,
  Combine,
  Contrast,
  Crop,
  Droplets,
  Eraser,
  File,
  FileCode,
  FileMinus,
  FileOutput,
  FilePlus,
  FileText,
  FileType2,
  Fingerprint,
  FlipHorizontal2,
  Gauge,
  GitCompare,
  Grid2x2,
  Hash,
  Image,
  ImageDown,
  Images,
  Info,
  Layers,
  LayoutGrid,
  Library,
  ListOrdered,
  Lock,
  LockOpen,
  MessageSquareText,
  Mic,
  Minimize2,
  MonitorPlay,
  Moon,
  NotebookPen,
  PanelTop,
  PencilLine,
  PencilRuler,
  PenLine,
  PenTool,
  Presentation,
  Receipt,
  RotateCw,
  Scaling,
  ScanSearch,
  ScanText,
  Scissors,
  Share2,
  Sheet,
  ShieldOff,
  Shuffle,
  Signature,
  Sparkles,
  SquareSlash,
  Stamp,
  Table,
  Table2,
  TextCursor,
  TextCursorInput,
  TextSearch,
  Ticket,
  Type,
  Volume2,
  Workflow,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";
import type { CategoryId } from "@/lib/tools/catalog";

const ICONS: Record<string, LucideIcon> = {
  Archive,
  BookMarked,
  BookOpen,
  Briefcase,
  Camera,
  ClipboardList,
  Code,
  Columns2,
  Combine,
  Contrast,
  Crop,
  Droplets,
  Eraser,
  FileCode,
  FileMinus,
  FileOutput,
  FilePlus,
  FileText,
  FileType2,
  Fingerprint,
  FlipHorizontal2,
  Gauge,
  GitCompare,
  Grid2x2,
  Hash,
  Image,
  ImageDown,
  Images,
  Info,
  Layers,
  LayoutGrid,
  Library,
  ListOrdered,
  Lock,
  LockOpen,
  MessageSquareText,
  Mic,
  Minimize2,
  MonitorPlay,
  Moon,
  NotebookPen,
  PanelTop,
  PencilLine,
  PencilRuler,
  PenLine,
  PenTool,
  Presentation,
  Receipt,
  RotateCw,
  Scaling,
  ScanSearch,
  ScanText,
  Scissors,
  Share2,
  Sheet,
  ShieldOff,
  Shuffle,
  Signature,
  Sparkles,
  SquareSlash,
  Stamp,
  Table,
  Table2,
  TextCursor,
  TextCursorInput,
  TextSearch,
  Ticket,
  Type,
  Volume2,
  Workflow,
  Wrench,
};

/** Each category gets its own ink colour for icon tiles. */
export const CATEGORY_TONE: Record<CategoryId, string> = {
  organize: "text-[#2d3bd6] bg-[#e9ebfd] dark:text-[#9aa3ff] dark:bg-[#1f2442]",
  optimize: "text-[#0f7b6c] bg-[#ddf3ee] dark:text-[#5fd3c0] dark:bg-[#11302b]",
  edit: "text-[#b4441b] bg-[#fbe9df] dark:text-[#ff9b73] dark:bg-[#3a1d12]",
  "to-pdf": "text-[#8a3ffc] bg-[#efe6ff] dark:text-[#c4a1ff] dark:bg-[#2a1d45]",
  "from-pdf": "text-[#0b6bcb] bg-[#e0effd] dark:text-[#7cbcff] dark:bg-[#132b44]",
  security: "text-[#a8233b] bg-[#fbe4e8] dark:text-[#ff8da1] dark:bg-[#3a141c]",
  ai: "text-[#7a5c00] bg-[#fbf1c7] dark:text-[#f0cf5a] dark:bg-[#33290c]",
  business: "text-[#1d6b35] bg-[#e1f3e6] dark:text-[#74d494] dark:bg-[#132d1c]",
  share: "text-[#4a5061] bg-[#eceef3] dark:text-[#b7bdcc] dark:bg-[#262a35]",
};

export function ToolIcon({ name, className, strokeWidth = 1.8 }: { name: string; className?: string; strokeWidth?: number }) {
  const Icon = ICONS[name] ?? File;
  return <Icon className={cn("size-5", className)} strokeWidth={strokeWidth} aria-hidden />;
}

export function IconTile({ name, category, size = "md", className }: { name: string; category: CategoryId; size?: "sm" | "md" | "lg"; className?: string }) {
  const s = size === "sm" ? "size-8 rounded-md [&_svg]:size-4" : size === "lg" ? "size-14 rounded-lg [&_svg]:size-7" : "size-10 rounded-md [&_svg]:size-5";
  return (
    <span className={cn("inline-flex shrink-0 items-center justify-center", s, CATEGORY_TONE[category], className)}>
      <ToolIcon name={name} />
    </span>
  );
}
