#!/usr/bin/env python3
"""
Compile ECMA-376 presetShapeDefinitions.xml (the formulas behind DrawingML's
187 preset shapes) into src/lib/pdf/drawingml/presets.ts.

    python3 scripts/gen-presets.py path/to/presetShapeDefinitions.xml

The XML ships with the ECMA-376 standard (Part 1, "OfficeOpenXML-DrawingMLGeometries")
and with LibreOffice's sources (oox/source/drawingml/customshapes/).

Each preset becomes one string: sections split by "|":
  adjust values   "name=formula;..."
  guides          "name=formula;..."
  text rectangle  "l t r b" (empty: the whole box)
  paths           "w h fill stroke~M x y L x y A wR hR stAng swAng Q .. C .. Z"
"""
import re
import sys
import xml.etree.ElementTree as ET

NS = "{http://schemas.openxmlformats.org/drawingml/2006/main}"


def gds(el):
    if el is None:
        return ""
    out = []
    for gd in el.findall(NS + "gd"):
        name, f = gd.get("name"), " ".join(gd.get("fmla").split())
        assert not re.search(r"[|;=~]", name + f), (name, f)
        out.append(f"{name}={f}")
    return ";".join(out)


def pt(el):
    p = el.find(NS + "pt")
    return [p.get("x"), p.get("y")]


def path(p):
    head = [p.get("w") or "0", p.get("h") or "0", p.get("fill") or "norm", "0" if p.get("stroke") in ("0", "false") else "1"]
    toks = []
    for c in p:
        tag = c.tag.replace(NS, "")
        if tag == "moveTo":
            toks += ["M", *pt(c)]
        elif tag == "lnTo":
            toks += ["L", *pt(c)]
        elif tag == "arcTo":
            toks += ["A", c.get("wR"), c.get("hR"), c.get("stAng"), c.get("swAng")]
        elif tag == "quadBezTo":
            for q in c.findall(NS + "pt"):
                toks += [q.get("x"), q.get("y")]
            toks.insert(len(toks) - 4, "Q")
        elif tag == "cubicBezTo":
            for q in c.findall(NS + "pt"):
                toks += [q.get("x"), q.get("y")]
            toks.insert(len(toks) - 6, "C")
        elif tag == "close":
            toks.append("Z")
        else:
            raise ValueError(tag)
    for t in toks:
        assert t is not None and not re.search(r"[|;=~\s]", t), t
    return " ".join(head) + "~" + " ".join(toks)


def main(src, dst):
    root = ET.parse(src).getroot()
    entries = []
    for shp in root:
        av = gds(shp.find(NS + "avLst"))
        gd = gds(shp.find(NS + "gdLst"))
        r = shp.find(NS + "rect")
        rect = " ".join(r.get(k) for k in ("l", "t", "r", "b")) if r is not None else ""
        paths = [path(p) for p in shp.find(NS + "pathLst").findall(NS + "path")]
        entries.append((shp.tag, "|".join([av, gd, rect, *paths])))
    lines = [
        "/* Generated by scripts/gen-presets.py from ECMA-376 presetShapeDefinitions.xml. Do not edit.\n * The shape formulas are (c) Ecma International, from ECMA-376 Part 1 (Office Open XML), whose\n * copyright license allows using them in products that implement the standard. */",
        "export const PRESETS: Record<string, string> = {",
    ]
    for name, s in entries:
        lines.append(f"  {name}: {s!r},".replace("'", '"') if '"' not in s else f"  {name}: {s!r},")
    lines.append("};")
    with open(dst, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{len(entries)} presets -> {dst}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else "src/lib/pdf/drawingml/presets.ts")
